version: '3.4'

services:
  appache:
    restart: always
    image: htppd
    build:
      context: ./httpd
      dockerfile: ./Dockerfile
    ports:
      - "41062:80"
      - "41061:22"
    links:
      - web-server
    networks:
      front-end:
        aliases:
          - httpserver

  web-server:
    image: web-server
    build:
      context: ./web-server
      dockerfile: ./Dockerfile
    networks:
      front-end:
        aliases:
          - web-server
      service-network:
        aliases:
          - web-server
      database-network:
        aliases:
          - web-server
    links:
      - automation-sheduler
      - database
      
  automation-sheduler:
    image: automation-sheduler
    build:
      context: ./automation
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    networks:
      service-network:
        aliases:
          - app
      chrome-network:
        aliases:
          - app
    links:
      - chrome

  chrome:
    image: zenika/alpine-chrome:latest
    command: [chromium-browser, "--headless", "--disable-gpu", "--no-sandbox", "--remote-debugging-address=0.0.0.0", "--remote-debugging-port=9222"]
    networks:
      chrome-network:
        aliases:
           - chrome

  database:
    image: postgres
    restart: unless-stopped
    networks:
      database-network:
        aliases:
          - database
    environment:
      POSTGRES_DB: mydb
      POSTGRES_PASSWORD: production_test
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    links:
      - adminer

  adminer:
    restart: always
    image: adminer
    networks:
      database-network:
        aliases:
          - adminer
    ports:
      - 8080:8080

networks:
  front-end:

  service-network:

  chrome-network:
  database-network: